# Generated by Django 4.1.4 on 2023-03-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_update',
            old_name='orderid',
            new_name='ord_id',
        ),
    ]
