# Generated by Django 4.1.4 on 2023-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_orderid_order_update_ord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update',
            name='ord_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
